### ISSUE TITLE
Small Request to DSSG-PT/Lead-team

### ISSUE THREAD

**Issue by OldMetalmind** [dssg-pt/dados-SICOeVM#30]
@dssg-pt/lead-team could you with your, DSSG account, make a commit to the Github Actions workflow so that my account is not spammed with 1 commit per day?

<img width="326" alt="Screenshot 2020-11-08 at 16 47 30" src="https://user-images.githubusercontent.com/404874/98471124-198e1700-21e2-11eb-928f-1e22a9cb2b2b.png">

The cause is that I own the last commit of the Github action and everyday is pushing, in my name, a new commit regarding the results.

It's a small, insignificant request but a bit vexatious, so I would be much appreciated 🙏

**Comment by dssgPT** [comment]
Tentei voltar a correr a ação agendada de hoje e deu erro provavelmente porque não há nada para atualizar. Bastaria fazer um commit qualquer para a pasta .github?

**Comment by dssgPT** [comment]
Parece que já está ,vou fechar
