### ISSUE TITLE
Age groups mixup

### ISSUE THREAD

**Issue by ghomem** [dssg-pt/dados-SICOeVM#37]
Hi,

There seems to be some kind of mixup between age groups. The age group '5a14anos' is showing values that can't be correct - they are too high and exhibit a pattern that is typical of much older groups.

![Screenshot_20220310_024934](https://user-images.githubusercontent.com/3352900/157572210-b93916ec-1fc6-4e2b-a0d7-34bb5ab37c4e.png)
![Screenshot_20220310_025053](https://user-images.githubusercontent.com/3352900/157572348-d5eba1dc-34d5-40ac-b9f3-52308f6b7f97.png)

Would you be so kind to check?

**Comment by ghomem** [comment]
You can check this data live here:

https://coviz.io/

(page 4)

**Comment by ghomem** [comment]
Plot made on a spreadsheet to illustrate the situation.

![Screenshot_20220310_035639](https://user-images.githubusercontent.com/3352900/157579497-f28c629f-34b4-4d9c-bd4a-62f0ba4265d9.png)

**Comment by ghomem** [comment]
Is this just a problem of having the headers sorted in alphabetical order instead of using the order that comes from the SiCO table?
![Screenshot_20220311_150211](https://user-images.githubusercontent.com/3352900/157882381-fb502329-0a5f-4bef-9948-1df32171479f.png)

**Comment by piresn** [comment]
Well spotted @ghomem. Unfortunately this bug also affected columns for distritos, causas and aces. It should be fixed now, the mortalidade.csv table will have the correct results tomorrow morning.

**Comment by ghomem** [comment]
thank you for the support @piresn . I will check this during the next days.

**Comment by ghomem** [comment]
@piresn the numbers now seem logical. I took a quick look at the csv file and compared it visually to the html table from the eVM website and using the mid-february dates (which should by now be stable) the values seem to match. You can have a look at the per age plots which are online now - intuitively the data seems OK. Thanks again for the help.
