### ISSUE TITLE
data not being updated?

### ISSUE THREAD

**Issue by ghomem** [dssg-pt/dados-SICOeVM#39]
Hi,

I was not paying attention for some time and realized today that there is now new data for any day after 03/02/2023.

![Screenshot_20230403_033011](https://user-images.githubusercontent.com/3352900/229392160-31a6b7d7-43e3-4f23-b780-150e480886bf.png)

Can you have a look please?

**Comment by piresn** [comment]
Thanks for noticing that @ghomem. There was an issue with GitHub Actions since the 04/02 that did not allow committing the csv files and logs. Hopefully it's now fixed. If there is still no data tomorrow (07/04) morning, please reopen the issue
